---
# This playbook updates a HFH server

-   hosts: local

    vars:
        local_user: '{{ ansible_user_id }}'
    
    vars_files:
    - vars/local.yml

    tasks:
    -   include_role:
            name: common
            apply:
                become: yes

    -   include_role:
            name: php
            apply:
                become: yes

    -   include_role:
            name: pip
            apply:
                become: yes

    -   include_role:
            name: docker
            apply:
                become: yes
        when: docker_install

    # -   name: "NPM und YARN"
    #     become: yes
    #     shell: "curl --silent --location https://rpm.nodesource.com/setup_10.x | bash - && yum -y install nodejs && curl -o- -L https://yarnpkg.com/install.sh | bash && npm install -g gulp && npm install -g yarn"


    -   name: "Ceck if symfony ci is installed"
        stat:
          path: /usr/local/bin/symfony
        register: symfony_cli_installed    

    # -   name: "Install Symfony Cli"
    #     command: wget https://get.symfony.com/cli/installer -O - | bash
    #     when: not symfony_cli_installed.stat.exists

    -   name: Download symfony installer
        get_url: 
            url: https://get.symfony.com/cli/installer
            dest: /tmp/symfony_cli_installer
        when: not symfony_cli_installed.stat.exists

    -   name: Execute the symfony installer
        script: /tmp/symfony_cli_installer
        when: not symfony_cli_installed.stat.exists

    -   name: Install globally
        command: mv /home/{{ ansible_user_id }}/.symfony/bin/symfony /usr/local/bin/symfony
        when: not symfony_cli_installed.stat.exists
        become: yes

    -   name: Remove the symfony installer
        file: path=/tmp/symfony_cli_installer state=absent
        