---
common_packages:
    - curl
    - wget
    - git
    - vim
    - perl
    - zip
    - unzip
    - ghostscript
    - thunderbird
    - ca-certificates
    - software-properties-common
    - apt-transport-https
    - zsh
    - mysql-client