---

nginx_service: "nginx"

nginx_worker_processes: 4
nginx_worker_connections: 1024
nginx_error_level: "warn"

nginx_dhparams_file: "/etc/nginx/dhparams.pem"
nginx_conf_file: "/etc/nginx/nginx.conf"

nginx_sites_dirs:
    - "/etc/nginx/sites-available"
    - "/etc/nginx/sites-enabled"

nginx_ssl_dir: "/etc/nginx/ssl"

with_ssl: "{{ nginx_ssl | default('true')}}"
