---
php_version: "7.4"

php_versions_to_purge:
    - php7.2-common

php_packages:
    - "php{{ php_version }}"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-common"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-gmp"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-ldap"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-pdo"
    - "php{{ php_version }}-phpdbg"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-sqlite3"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-xsl"
    # - "php{{ php_version }}-mcrypt"
    - php-apcu
    - php-igbinary
    - php-redis
    - php-xdebug

php_fpm_service: "php-fpm"

php_session_handler: "memcached"

php_fpm_pool_conf_path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
php_cli_conf_dir: "/etc/php/{{ php_version }}/cli/conf.d"
php_cli_ini_path: "/etc/php/{{ php_version }}/cli/php.ini"
php_opcache_ini_path: "{{ php_cli_conf_dir }}/10-opcache.ini"
php_memcached_ini_path: "{{ php_cli_conf_dir }}/10-memcached.ini"
php_fpm_socket_path: "/var/run/php-fpm/php-fpm.sock"
php_fpm_wsdl_cache_dir: "/tmp"
php_fpm_memory_limit: "1024M"
php_fpm_max_execution_time: 600
php_fpm_realpath_cache_size: "4096K"
php_fpm_realpath_cache_ttl: 600
php_fpm_sess_lock_wait_min: 330
php_fpm_sess_lock_wait_max: 600
php_fpm_sess_lock_retries: 250
php_fpm_sess_lock_expire: "{{php_fpm_max_execution_time}}"
php_fpm_conf_user: "{{ local_user }}"
php_fpm_conf_group: "www-data"
php_fpm_conf_mode: "0660"

php_max_input_vars: 5000

memcached_packages:
    - "memcached"
    - "php-memcache"
    - "php-memcached"

memcached_user: "memcached"
memcached_config_file: "/etc/sysconfig/memcached"
memcached_ini_file: "/etc/php.d/50-memcached.ini"
memcached_port: 11211
memcached_listen_ip: 127.0.0.1

memcached_memory_limit: 64
memcached_connections: 1024

memcached_log_file: "/var/log/memcached.log"
memcached_log_verbosity: ""
